### ISSUE TITLE
The api endpoint for images has changed

### ISSUE THREAD

**Issue by JasonLWalker** [TapwaveZodiac/novelaiUKB#11]
NovelAI recently changed the endpoint for image generation to https://image.novelai.net/ai/generate-image

It's mentioned at the top of the api page that the image URL is different, but it may be good to restate it where the endpoint is described as well.

**Comment by Aedial** [comment]
OK, might be time to rework on the page a little. Will correct this points and add missing details, as I haven't touched it in a while.
