### ISSUE TITLE
StoryContent contains MessagePack data

### ISSUE THREAD

**Issue by JasonLWalker** [TapwaveZodiac/novelaiUKB#12]
The response from the /user/storycontent endpoint contains a field called "document" that is Base64 encoded (and I believe deflated too). When decoded, the field contains a blob byte array that must be unpacked using a customized version of MessagePack.

The full MessagePack schema can be found at:
https://github.com/msgpack/msgpack/blob/master/spec.md

The version that NovelAI seems to use appears to be a custom extended version of:
https://github.com/kriszyp/msgpackr

I have implemented a working unpacker and submitted it as a pull request to Draco18's C# library:
https://github.com/Draco18s/NovelAPI/pull/14

Additionally, I have a working C# sample Implementation of Draco18's library at:
https://github.com/JasonLWalker/net.novelai.api.testsuite/tree/MessagePackr

**Comment by Aedial** [comment]
According to Chris (27/06/2023 - https://discord.com/channels/836774308772446268/837402685824565278/1123331549341958154):
> That's gonna be a bit tricky. `document` is the base64 of a `msgpackr` buffer packed with a couple custom extensions for the internal document structures. You'll need to define those extensions to unpack it with it.
> Though you can probably get away with defining them as just passthrough functions since all they're doing is assigning class instances, which you don't necessarily need if you just want to read the contents. The extensions you need to define are `20`, `30`, `31`, `40`, `41`, and `42`. See https://github.com/kriszyp/msgpackr#custom-extensions
> You'll also have to enable the  `bundleStrings` and `moreTypes` options.
> After that it should be relatively straightforward though. In the document is a map of sections containing their text, and an order array. Put the section entries in order and you're pretty much done.

So far I haven't been able to decompress it in Python, but if you have a working implementation it could be added.

**Comment by JasonLWalker** [comment]
I can confirm that 20, 30, 31, 30, 41 and 42 do work with just passthroughs as long as you are not trying to map the results to some sort of strongly-typed structure while decoding. In C#, I simply kept the structure type as a JObject, (a C# JSON node), and didn't worry about trying to map it to a stronger structure type.

Also, Draco18 has merged my pull request into the main code branch, so there is now a working implementation if you want to reference it. I ported most of Chris Zyp's JavaScript unpacker to C#, and then created a new class that inherited from that to handle the NovelAI specific extensions.

**Comment by JasonLWalker** [comment]
@Aedial, I have been working on a python version of the NovelAI unpacker, and have managed to successfuly unpack 2 samples. I will try to submit a pull request soon to your novelai-api project. (as soon as I have the appropriate tests written.)
