### ISSUE TITLE
"Starting your First Story" first image is too wide

### ISSUE THREAD

**Issue by Mach565** [TapwaveZodiac/novelaiUKB#5]
On my 1080p screen and even with the table of contents hidden, I still have to scroll sideways to see the other edge of the image, see below.
![image](https://github.com/TapwaveZodiac/novelaiUKB/assets/97276027/a39e6ded-aed5-4af2-8988-15fc9c8575f2)
As you can see, the left side of the image (the one with the stories list) is cut off.

**Comment by TapwaveZodiac** [comment]
Resolved.
